### ISSUE TITLE
Template de demande de feedback

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#300]
# Besoin

Faciliter la demande de feedback

# Solution

Avoir des templates différents pour des contextes différents :
- entretien annuel
- fin de mission
- début de mission
- arrivée à zenika
- entretien technique
- etc

**Comment by avine** [comment]
Voici les textes que tu m'as envoyé par Slack : 

### Fin de mission

Comme tu le sais, ma mission se termine bientôt et j’aimerai avoir ton feedback sur ma prestation. Ces retours me seront grandement utiles, cela m’aidera à m’améliorer.

### Entretien annuel

J’ai bientôt mon entretien annuel et afin de le préparer j’aimerais avoir ton feedback sur ce que je fais bien et ce que je pourrais améliorer.

### Débuts à Zenika

Si tu as quelques minutes, j’aimerais que tu me fasses un retour sur mes débuts à Zenika, que ce soit un axe d’amélioration, quelque chose que tu veux partager, ou quelque chose de positif que tu souhaites exprimer. Ces retours me seront grandement utiles, cela m’aidera à m’améliorer.

### Nouvelle mission

Cela fait désormais quelques temps que j’ai démarré ma mission, et dans ce cadre je souhaiterais avoir ton retour pour pouvoir m’améliorer.

### Conférence

Tu as assisté récemment à une conférence que j’ai présenté, j’aimerais bien avoir ton feedback sur cette présentation.

**Comment by avine** [comment]
Je te propose les modifications suivantes (ordre et contenu des templates).
Mais dis-moi ce que tu en penses et si tu préfères que je reprenne tes textes tels quels.

A noter que tous les templates commencent par "_Bonjour_," et terminent par "_Merci par avance_".

---

### Débuts à Zenika

J'aimerais avoir ton feedback sur mes débuts à Zenika. Cela peut être quelque chose de positif que tu as remarqué ou quelque chose que je pourrais améliorer.

### Début de mission

Cela fait un moment que j'ai commencé ma mission et j'aimerais avoir ton feedback sur ce que je fais bien et ce que je pourrais améliorer.

### Fin de mission

Comme tu le sais, ma mission se termine bientôt et j'aimerais avoir ton feedback sur ma prestation, ce que j'ai réussi et ce que je pourrais améliorer.

### Entretien annuel

En vue de mon entretien annuel qui a lieu bientôt, j'aimerais avoir ton feedback sur ce que je fais bien et ce que je pourrais améliorer.

### Conférence

Récemment, j'ai donné une conférence à laquelle tu as assisté et j'aimerais avoir ton feedback sur ce qui a bien fonctionné et ce que je pourrais améliorer.

**Comment by avine** [comment]
Et la version anglaise traduite par Deepl (avec quelques modifs) donnerai ça : 
---

### Starting at Zenika

If you have a few minutes, I'd like your feedback on my start at Zenika. It could be something positive you've noticed or something I could do better.

### Start of assignment

It's been a while since I started my assignment and I'd like your feedback on what I'm doing well and what I could do better.

### End of assignment

As you know, my assignment is coming to an end soon and I'd like your feedback on what I've done well and what I could do better.

### Annual review

With my annual review coming up, I'd like your feedback on what I'm doing well and what I could do better.

### Conference

I recently gave a talk which you attended and I'd like your feedback on what went well and what I could do better.

**Comment by avine** [comment]
Concernant l'ordre des templates, ça donnerait ça : 
<img width="298" alt="Capture d’écran 2024-04-08 à 11 26 55" src="https://github.com/Zenika/feedzback/assets/1133214/beae09e2-a8d4-4275-882d-13ce43ab875b">
